import {
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  Baby,
  Barbell,
  BatteryHigh,
  Bell,
  BookmarkSimple,
  Buildings,
  Bug,
  Camera,
  CaretDown,
  CaretRight,
  CellSignalFull,
  ChatsCircle,
  CheckCircle,
  Circle,
  Clock,
  Code,
  CookingPot,
  FileText,
  FirstAid,
  Flag,
  Gear,
  HandHeart,
  HandWaving,
  Handshake,
  Hammer,
  Heartbeat,
  House,
  IconProps,
  IconWeight,
  ImageSquare,
  Key,
  Lightning,
  Link,
  Lock,
  MagicWand,
  MagnifyingGlass,
  MapPin,
  Medal,
  Megaphone,
  Note,
  Package,
  PaintRoller,
  Palette,
  PaperPlaneTilt,
  PenNib,
  Phone,
  PhoneCall,
  Plant,
  Plus,
  PlusCircle,
  Question,
  Scissors,
  Sparkle,
  SealCheck,
  ShareNetwork,
  ShieldCheck,
  SignOut,
  SlidersHorizontal,
  SquaresFour,
  Star,
  SteeringWheel,
  Storefront,
  TShirt,
  TelegramLogo,
  Translate,
  Tray,
  Truck,
  User,
  UsersThree,
  Wall,
  Warning,
  WarningCircle,
  WhatsappLogo,
  WifiHigh,
  Wrench,
  X,
  XCircle,
} from 'phosphor-react-native';
import type { ComponentType } from 'react';

export type { IconWeight };

/** Maps the design's `ph-*` icon strings to phosphor-react-native components. */
const REGISTRY: Record<string, ComponentType<IconProps>> = {
  'ph-wrench': Wrench,
  'ph-lightning': Lightning,
  'ph-paint-roller': PaintRoller,
  'ph-hammer': Hammer,
  'ph-key': Key,
  'ph-sparkle': Sparkle,
  'ph-baby': Baby,
  'ph-t-shirt': TShirt,
  'ph-plant': Plant,
  'ph-bug': Bug,
  'ph-truck': Truck,
  'ph-steering-wheel': SteeringWheel,
  'ph-camera': Camera,
  'ph-cooking-pot': CookingPot,
  'ph-palette': Palette,
  'ph-scissors': Scissors,
  'ph-pen-nib': PenNib,
  'ph-code': Code,
  'ph-megaphone': Megaphone,
  'ph-map-pin': MapPin,
  'ph-caret-down': CaretDown,
  'ph-caret-right': CaretRight,
  'ph-bookmark-simple': BookmarkSimple,
  'ph-magnifying-glass': MagnifyingGlass,
  'ph-sliders-horizontal': SlidersHorizontal,
  'ph-arrow-right': ArrowRight,
  'ph-arrow-left': ArrowLeft,
  'ph-arrow-clockwise': ArrowClockwise,
  'ph-seal-check': SealCheck,
  'ph-house': House,
  'ph-squares-four': SquaresFour,
  'ph-plus-circle': PlusCircle,
  'ph-plus': Plus,
  'ph-user': User,
  'ph-phone': Phone,
  'ph-phone-call': PhoneCall,
  'ph-whatsapp-logo': WhatsappLogo,
  'ph-star': Star,
  'ph-clock': Clock,
  'ph-medal': Medal,
  'ph-image-square': ImageSquare,
  'ph-check-circle': CheckCircle,
  'ph-x-circle': XCircle,
  'ph-x': X,
  'ph-buildings': Buildings,
  'ph-users-three': UsersThree,
  'ph-shield-check': ShieldCheck,
  'ph-hand-heart': HandHeart,
  'ph-paper-plane-tilt': PaperPlaneTilt,
  'ph-chats-circle': ChatsCircle,
  'ph-chats': ChatsCircle,
  'ph-share-network': ShareNetwork,
  'ph-warning-circle': WarningCircle,
  'ph-magic-wand': MagicWand,
  'ph-bell': Bell,
  'ph-tray': Tray,
  'ph-translate': Translate,
  'ph-question': Question,
  'ph-flag': Flag,
  'ph-storefront': Storefront,
  'ph-gear': Gear,
  'ph-sign-out': SignOut,
  'ph-telegram-logo': TelegramLogo,
  'ph-handshake': Handshake,
  'ph-note': Note,
  'ph-file-text': FileText,
  'ph-lock': Lock,
  'ph-warning': Warning,
  'ph-hand-waving': HandWaving,
  'ph-link': Link,
  'ph-cell-signal-full': CellSignalFull,
  'ph-wifi-high': WifiHigh,
  'ph-battery-high': BatteryHigh,
  // Ontology-aligned category icons (Task 5).
  'ph-wall': Wall,
  'ph-package': Package,
  'ph-first-aid': FirstAid,
  'ph-heartbeat': Heartbeat,
  'ph-barbell': Barbell,
};

export interface IconComponentProps {
  name: string;
  size?: number;
  color?: string;
  weight?: IconWeight;
}

/**
 * Renders a Phosphor icon by its design `ph-*` name.
 * `weight` mirrors the prototype's regular / bold / fill variants.
 */
export function Icon({ name, size = 18, color = colorFallback, weight = 'regular' }: IconComponentProps) {
  const Cmp = REGISTRY[name] || Circle;
  return <Cmp size={size} color={color} weight={weight} />;
}

const colorFallback = '#102E25';
